EVOLUTION_EVENT_RUN_RECORDED = "evolution.run.recorded"
EVOLUTION_EVENT_RUN_FAILED = "evolution.run.failed"
EVOLUTION_EVENT_FOLLOWUP_REQUESTED = "evolution.followup.requested"
EVOLUTION_EVENT_EXECUTION_PROJECTED = "evolution.execution.projected"
EVOLUTION_EVENT_VERIFICATION_PROJECTED = "evolution.verification.projected"
EVOLUTION_EVENT_DECISION_RECORDED = "evolution.decision.recorded"

__all__ = [
    "EVOLUTION_EVENT_DECISION_RECORDED",
    "EVOLUTION_EVENT_EXECUTION_PROJECTED",
    "EVOLUTION_EVENT_FOLLOWUP_REQUESTED",
    "EVOLUTION_EVENT_RUN_FAILED",
    "EVOLUTION_EVENT_RUN_RECORDED",
    "EVOLUTION_EVENT_VERIFICATION_PROJECTED",
]
