"""Compatibility facade for artifact domain models."""

from .domain.artifact.models import (
    ARTIFACT_RECORD_KIND_ATOMIC,
    ARTIFACT_RECORD_KIND_COMPOSITE,
    ARTIFACT_RECORD_SCHEMA_VERSION,
    ARTIFACT_STATE_CANDIDATE,
    ARTIFACT_STATE_DRAFT,
    ARTIFACT_STATE_INVALID,
    ARTIFACT_STATE_PROMOTABLE,
    ARTIFACT_STATE_PROMOTED,
    ARTIFACT_STATE_STALE,
    ARTIFACT_STATE_VERIFIED,
    INVARIANT_STATUS_FAILED,
    INVARIANT_STATUS_PASSED,
    INVARIANT_STATUS_PENDING,
    VERIFICATION_CLAIM_STATUS_FAILED,
    VERIFICATION_CLAIM_STATUS_PASSED,
    VERIFICATION_CLAIM_STATUS_PENDING,
    ArtifactInvariantRecord,
    ArtifactLineage,
    ArtifactRecord,
    ArtifactRef,
    CollectionSlotBinding,
    CompositeArtifactRecord,
    FeatureChangeSlotBindings,
    NamedSlotBinding,
    TaskRunRef,
    TaskSpecRef,
    VerificationClaimRecord,
)
from .application.codecs.artifacts import decode_artifact_record as load_artifact_record

__all__ = [
    "ARTIFACT_RECORD_KIND_ATOMIC",
    "ARTIFACT_RECORD_KIND_COMPOSITE",
    "ARTIFACT_RECORD_SCHEMA_VERSION",
    "ARTIFACT_STATE_CANDIDATE",
    "ARTIFACT_STATE_DRAFT",
    "ARTIFACT_STATE_INVALID",
    "ARTIFACT_STATE_PROMOTABLE",
    "ARTIFACT_STATE_PROMOTED",
    "ARTIFACT_STATE_STALE",
    "ARTIFACT_STATE_VERIFIED",
    "INVARIANT_STATUS_FAILED",
    "INVARIANT_STATUS_PASSED",
    "INVARIANT_STATUS_PENDING",
    "CollectionSlotBinding",
    "ArtifactInvariantRecord",
    "ArtifactLineage",
    "ArtifactRecord",
    "ArtifactRef",
    "CompositeArtifactRecord",
    "FeatureChangeSlotBindings",
    "NamedSlotBinding",
    "TaskRunRef",
    "TaskSpecRef",
    "VerificationClaimRecord",
    "VERIFICATION_CLAIM_STATUS_FAILED",
    "VERIFICATION_CLAIM_STATUS_PASSED",
    "VERIFICATION_CLAIM_STATUS_PENDING",
    "load_artifact_record",
]
