"""Compatibility facade for artifact DSL models."""

from .domain.artifact.dsl import (
    COMPILED_OBLIGATION_KIND,
    DSL_SCHEMA_VERSION,
    EXECUTION_POLICY_KIND,
    INPUT_CONTRACT_KIND,
    INPUT_MODE_FORBIDDEN,
    INPUT_MODE_OPTIONAL,
    INPUT_MODE_REQUIRED,
    MATERIALIZED_INPUT_SET_KIND,
    OBLIGATION_INTENT_KIND,
    OBLIGATION_SPEC_KIND,
    PROTOCOL_SPEC_KIND,
    CompiledObligation,
    ExecutionPolicy,
    InputContract,
    MaterializedInputSet,
    ObligationIntent,
    ObligationSpec,
    ProducedArtifactSpec,
    ProtocolSpec,
    RefSelector,
)

__all__ = [
    "COMPILED_OBLIGATION_KIND",
    "DSL_SCHEMA_VERSION",
    "EXECUTION_POLICY_KIND",
    "INPUT_CONTRACT_KIND",
    "INPUT_MODE_FORBIDDEN",
    "INPUT_MODE_OPTIONAL",
    "INPUT_MODE_REQUIRED",
    "MATERIALIZED_INPUT_SET_KIND",
    "OBLIGATION_INTENT_KIND",
    "OBLIGATION_SPEC_KIND",
    "PROTOCOL_SPEC_KIND",
    "CompiledObligation",
    "ExecutionPolicy",
    "InputContract",
    "MaterializedInputSet",
    "ObligationIntent",
    "ObligationSpec",
    "ProducedArtifactSpec",
    "ProtocolSpec",
    "RefSelector",
]
