"""Compatibility facade for feature-change obligation compilation."""

from .application.artifacts.obligations import (
    DEFAULT_FEATURE_CHANGE_PROTOCOL_DECLARATION,
    FEATURE_CHANGE_ARTIFACT_TYPE,
    OBLIGATION_SPEC_BIND_IMPLEMENTATION_CANDIDATES,
    OBLIGATION_SPEC_BIND_REQUIRED_TESTS,
    OBLIGATION_SPEC_COLLECT_APPROVALS,
    OBLIGATION_SPEC_RECOMPOSE_FEATURE_CHANGE,
    OBLIGATION_SPEC_REPLACE_INVALID_INPUTS,
    OBLIGATION_SPEC_RESELECT_IMPLEMENTATION,
    OBLIGATION_SPEC_REVERIFY_REQUIRED_CLAIMS,
    OBLIGATION_SPEC_REVERIFY_STALE_INPUTS,
    OBLIGATION_SPEC_SELECT_IMPLEMENTATION,
    OBLIGATION_SPEC_VERIFY_COMPOSITE_FEATURE,
    OBLIGATION_SPEC_VERIFY_CROSS_FEATURE,
    OBLIGATION_SPEC_VERIFY_LOCAL_FEATURE,
    fingerprint_materialized_inputs,
    obligation_intents_from_feature_change_evaluation,
)
from .composition.feature_change_dsl import (
    compile_feature_change_obligation,
    compile_feature_change_obligations,
    default_feature_change_protocol_spec,
    feature_change_obligation_specs_by_id,
    load_feature_change_protocol_spec_declaration,
)

__all__ = [
    "FEATURE_CHANGE_ARTIFACT_TYPE",
    "DEFAULT_FEATURE_CHANGE_PROTOCOL_DECLARATION",
    "OBLIGATION_SPEC_BIND_IMPLEMENTATION_CANDIDATES",
    "OBLIGATION_SPEC_BIND_REQUIRED_TESTS",
    "OBLIGATION_SPEC_COLLECT_APPROVALS",
    "OBLIGATION_SPEC_RECOMPOSE_FEATURE_CHANGE",
    "OBLIGATION_SPEC_REPLACE_INVALID_INPUTS",
    "OBLIGATION_SPEC_RESELECT_IMPLEMENTATION",
    "OBLIGATION_SPEC_REVERIFY_REQUIRED_CLAIMS",
    "OBLIGATION_SPEC_REVERIFY_STALE_INPUTS",
    "OBLIGATION_SPEC_SELECT_IMPLEMENTATION",
    "OBLIGATION_SPEC_VERIFY_CROSS_FEATURE",
    "OBLIGATION_SPEC_VERIFY_COMPOSITE_FEATURE",
    "OBLIGATION_SPEC_VERIFY_LOCAL_FEATURE",
    "compile_feature_change_obligation",
    "compile_feature_change_obligations",
    "default_feature_change_protocol_spec",
    "feature_change_obligation_specs_by_id",
    "fingerprint_materialized_inputs",
    "load_feature_change_protocol_spec_declaration",
    "obligation_intents_from_feature_change_evaluation",
]
